### ISSUE TITLE
Should we use an explicit export statement instead of local/global to define what functions are exported?

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#184]
For example, instead of 

```
function foo() end
function bar() end
```

we could use 

```
local function foo() end
local function bar() end
export foo, bar
```

The "local" specifier for would now be required for toplevel functions, making clear that they are not assigned to a global variable. To export the functions, we would use an explicit `export` list at the end of the module. 

The main thing that draws me to this idea is that it would allow function declaration statements to work the same in the toplevel and inside other functions, when we implement closures.  I also think the export statement would bring Pallene a bit closer to Lua. Pallene would stop giving special treatment to toplevel globals, and the export statement at the end of the module is similar to the `return` statement that Lua modules already use. What do you think?

**Comment by ahmedkrmn** [comment]
I believe this is a very appropriate change that should be made.

**Comment by gligneul** [comment]
> The "local" specifier for would now be required for toplevel functions, making clear that they are not assigned to a global variable. 

What happens when the user declares a function without the `local` modifier? I expect that the compiler creates a closure and sets it to the appropriate global variable. Are we implementing this behavior? Or will it be an error? 

---

> To export the functions, we would use an explicit export list at the end of the module.

I like the idea since it covers one way of implementing modules in Lua. A to-Lua compiler could just replace the export with a return statement. However, are we going to allow the export only as the last statement in the top level? What happens when the user write more than one export? For instance:
```
local function foo() end
export foo
local function bar() end
export bar
```

What happens when the user doesn't write the export statement? Will the compiler create an empty module? Will it be an error?

---

One more thing: when I'm programming in Lua I prefer to declare the module at the top of the file and declare the functions with the module name:
```
local my_module = {}
function my_module.f() end
return my_module
```
How is this going to be translated to Pallene? Even if we don't implement this feature at first, it is important to consider this case and preferably design how it is going to be. My suggestion is something like:
```
module my_module
function my_module.f() end
```

If the `export` statement is going to be a special statement that can only be written in the end of the top-level, the `module` statement could also be a special statement that is written in the beginning of the top-level.

**Comment by gligneul** [comment]
I suggest that we decide what we are going to do, create the appropriate issues and then close this one.

**Comment by hugomg** [comment]
> I expect that the compiler creates a closure and sets it to the appropriate global variable. Are we implementing this behavior? Or will it be an error?

I agree that if we add global variables in the future we should make a function declared without a `local` be an assignment to a global variable, just like in Lua. But for now I would be in favor of requiring all toplevel functions to be declared with `local`, and make it be an error if it doesn't have the `local`.

> However, are we going to allow the export only as the last statement in the top level? What happens when the user write more than one export? For instance:

We could follow the precedent of  Javascript. Multiple export declarations in the file work the same as one export at the end of the file that exports everything.

The corner case to be careful about is variable shadowing. For example, if we allow the following then the export would export the first "foo", not the second.

    local function foo() end
    export foo
    local function foo() end

There should also be a restriction that the same name cannot be exported more than once. This restriction will replace the current restriction that we have about not having the same name declared twice in the toplevel.

Following Javascript, we could also allow `export function foo() end` as syntactic sugar for 

    local function foo() end
    export foo

> What happens when the user doesn't write the export statement? Will the compiler create an empty module? Will it be an error?

I suggest that in the absense of an export statement then it will work as if there were a `return nil` at the end of the module. This would allow the option of modules that don't export anything, and are only used for side effects. One reason to do this is that in the future we might want to allow standalone Pallene programs where the "main" function is in Pallene. For example, a hello world program written in Pallene.

> When I'm programming in Lua I prefer to declare the module at the top of the file and declare the functions with the module name. How is this going to be translated to Pallene?

In Haskell there is a restriction that the module name declared inside the file has to match the file name that it is in. But I think I'd prefer to avoid this redundancy and make it possible to export functions without needing to write the module name.

For example,

```
local function foo() end
export foo
```

or 

```
export function foo() end
```

**Comment by hugomg** [comment]
> I suggest that we decide what we are going to do, create the appropriate issues and then close this one.

Sure. I can write down a more detailed specification for the export statements in a separate issue, so it is easier to keep track of it.

**Comment by gligneul** [comment]
Pallene is based on Lua, not in Javascript. I was starting to like the export idea but now it seems that we are going in the wrong direction. I'm not comfortable adding semantics that are based in languages other than Lua to Pallene. Specially because this semantics is becoming complex and full of caveats.

Adding `export` invalidates the gradual guarantee from Pallene: if we remove the exports the code won't be Lua. Besides the theoretical reasoning, adding this feature will be confusing to programmers using both Pallene and Lua. With a feature like this the programmer will be writing code in Pallene that is completely different from what he/she writes in Lua. This is more conceptual overhead to a Lua programmer that would like to adopt Pallene.

Also, adding this special case to the top-level will also make more difficult to make it iterative later. We would compromise the language with semantics that forces the top-level to be something special. The top-level is somewhat special now, but I think that we should be going in the direction to make it like a plain function body. 

To solve the export problem, why don't we add a special return statement to the top-level? This statement could receive a single top-level function or a table-like record of functions:
```
local function foo() end
local function bar() end
return {foo=foo, bar=bar}
``` 
We could have a module that only returns one function as well:
```
local function foo() end
return foo
```

This statement could be something special for now, but at least it will make Pallene compatible with Lua. We would be back to "removing types from a Pallene program allows the Lua interpreter to run it".

**Comment by gligneul** [comment]
To be more clear, the top-level could return a value o the type `module-decl`. This is a type the will be compiled into a plain Lua table. This type can be created with `{}` or with `{fname = fvalue, ...}`, where `fname` is the function name and `fvalue` is the function value. Also, this type implements the operator `.`, allowing programmers to add functions to the module-declaration and indexing them later. This type doesn't need to be a special top-level feature, it could be declared anywhere.

**Comment by hugomg** [comment]
> . I was starting to like the export idea but now it seems that we are going in the wrong direction. I'm not comfortable adding semantics that are based in languages other than Lua to Pallene.

I think this ultimately comes down to whether we want to introduce new syntax for the module system, or if we want to go the Typed Lua route and reuse existing Lua syntax as much as possible.

If we go for the new syntax, then I think Javascript would be a valid inspiration, since its module system was designed to answer many of the same problems as in Lua. 

> Adding export invalidates the gradual guarantee from Pallene

With type annotations, there is a reasonable expectation that converting from Pallene to Lua means erasing the type annotations. But with a new syntax like import or export I think the natural expectation is that import becomes require, and exports would be collected together in a return statement.

I think the new-syntax vs existing-syntax question has more to do with familiarity and learning curve than with the gradual guarantee.

> To solve the export problem, why don't we add a special return statement to the top-level?

I dislike having to write every exported function's name three times, and and forcing all the function exports to be at the bottom of the file, far away from the function definitions. This is why in Lua I typically use the `local modname={}; function modname.foo() end` approach.

That said, if we were to go with the "Typed Lua" approach, I would prefer a simple `return {...}` statement instead of the `local modname={}; return modname` pattern. In the second option we the exported functions are declared with `function modname.f() end` and it may give the impression that the functions can be monkey patched by external modules.

> We could have a module that only returns one function as well:

In Javascript the syntax for that is `export default foo`.

However, I wonder if mmaywe we should not allow this feature in Pallene. If we allow returning an arbitrary table object (just like in Lua) then it means that the exported functions can be monkey patched.

> To be more clear, the top-level could return a value of the type moduledecl

I'd prefer to not extend the type system. We should make sure that there is no way to store a module in a variable, to receive or return a module from a function, or to assign a module to an array or table element.

**Comment by gligneul** [comment]
> I'd prefer to not extend the type system. We should make sure that there is no way to store a module in a variable, to receive or return a module from a function, or to assign a module to an array or table element.

I don't see the issue. Having a type for module declarations would allow us to write modules just like Lua. The programmer would be able to write both:
```
local m: module_decl = {}
function m.foo() end
return m
```
and
```
local function foo() end
return {f1 = foo}
```

**Comment by gligneul** [comment]
I believe that the beauty of Pallene is that we were able to create another language just by adding types to Lua. Adding new constructs would take that away, specially if we were able to avoid them.

**Comment by hugomg** [comment]
> Having a type for module declarations would allow us to write modules just like Lua

What I don't like about the `module_decl` type is that it suggests that module tables are first-class values. Are we allowed to create an `{module_decl}`, or a function with type `string->module_decl`? Can we create multiple toplevel variables with type `module_decl`? Furthermore, what would be the typing rules for `module_decl`?

If we're gonna stick to strict Lua syntax I'd rather go with `return {...}`, which is simple and avoids all these problems.

**Comment by gligneul** [comment]
> Are we allowed to create an {module_decl}, or a function with type string->module_decl?

Why bother prohibiting? It would be compiled to a plain table anyway.

> Can we create multiple toplevel variables with type module_decl?

It would be like creating multiple tables.

> Furthermore, what would be the typing rules for module_decl?

The tricky part would be to retrieve the type of a function of the module. For instance, what the compiler should do in the following case?

``
local m: module_decl = {}
function m.f() end -- We add `f` to `m`
function m.g()
  -- How do we know the type of `f`?
  -- Should we modify the type of  `m` after the assignment? 
  m.f()
end
return m
```

I'm not sure how to solve it now, but I feel that creating a type for modules is the right direction.

> If we're gonna stick to strict Lua syntax I'd rather go with return {...}, which is simple and avoids all these problems.

Indeed, a special `return {...}` in the top-level could be the first step. The module type could come later. The nice thing is that our Pallene benchmarks would be more close to the Lua ones.

**Comment by hugomg** [comment]
> Why bother prohibiting? It would be compiled to a plain table anyway

I can't think of many situations where that flexibility would be very useful, but it would cause us a lot of pain when optimizing things.  Pallene likes to be able to know at compile time what the functions are, to be able to call them directly without needing to look up a table field every time. Having the module tables be treated as a regular table makes this more challenging.

> It would be like creating multiple tables

Sure, but how often is that useful? Most of the time we only need one module table.

I feel like the main motivation for having this feature use the type system is because the syntax for `local x: module_type = {}` maps to Lua by just erasing the type annotation. However, I don't think this is worth the cost of the extra weirdness of having `module_type` be a type. Like being able to create two module tables in a single file, or being able to write `typealias foo = module_type`.

If we choose to go with that syntax, I think it might be simpler to just have the parser treat `local x : module_type` as a special kind of module declaration, distinct from regular variable declarations. But then we'd have the issue of having something look like a type but not actually be a type. My personal preference would be to avoid this dilemma and go with `return {...}` or `export`.

> Should we modify the type of  `m` after the assignment? I'm not sure how to solve it now, but I feel that creating a type for modules is the right direction.

I expect it would end up looking very similar to one of Typed Lua's table types, which was designed to solve this common situation of initializing a table by starting with `{}` and then assigning one field at a time. However, I don't remember exactly what it was. This is one of those Typed Lua things that I never could understand 100%.

> Indeed, a special return {...} in the top-level could be the first step

It appears that everyone agrees that the `return { ... }` syntax is a good idea. What do you think about  implementing that for now and leaving the question over alternative syntaxes for later?

**Comment by gligneul** [comment]
> If we choose to go with that syntax, I think it might be simpler to just have the parser treat local x : module_type as a special kind of module declaration, distinct from regular variable declarations. But then we'd have the issue of having something look like a type but not actually be a type. My personal preference would be to avoid this dilemma and go with return {...} or export.

I understand your points. Indeed it might be simpler to add a new syntax so we can keep the type system simple. However, if we go in this direction the top-level will always be something special, do we want this?

Also, I still don't like the export semantics because it doesn't resemble Lua. We would be importing semantics from other languages, which will be confusing for Lua programmers. Instead, we could create a special module syntax similar to what I proposed earlier. For instance:

```
module m
function m.f() end
return m
```

The statement `module m` could easily be compiled in Lua to `local m = {}`, and the rest of the could would be the same.

> It appears that everyone agrees that the return { ... } syntax is a good idea. What do you think about implementing that for now and leaving the question over alternative syntaxes for later?

What do you have in mind? Will it be a key-value table initialisation or just an array with the function names? I prefer the key-value initialisation because it is more Lua-like even though it is a little bit more verbose.

**Comment by hugomg** [comment]
> Instead, we could create a special module syntax similar to what I proposed earlier. For instance: `module m`.

We'd have to flesh out the details, but I think this idea is promising. 

> I prefer the key-value initialisation because it is more Lua-like even though it is a little bit more verbose.

Yes I was also thinking of the key-value syntax, for exactly this reason.
