### ISSUE TITLE
Rename things Titan -> Pallene

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#22]
We should rename the "Titan" stuff in this repo to "Pallene", to avoid confusion.

- [x] titanc → pallenec
- [x] luarocks spec file
- [x] extension: .titan → .pallene
- [x] source directory: titan-compiler → pallene
- [x] C runtime library (tcore → pallene_core; titanlib → pallenelib)
- [x] C runtime functions (titan\_\* → pallene\_\*)
- [x] Update manual.md (Hugo is working on this)
- [x] "_titan" stuff in coder.lua, coder_spec.lua, etc (see `grep -Ri titan`)
- [x] Authors in LICENSE

~~It might still be a good idea to maintain the `.titan` extension though.~~

**Comment by gligneul** [comment]
I would not mantain the `.titan` extension, it gives the impression that pallene is just another compiler implementation of the Titan language. But it is not the case, since this is a slightly different language.
Also, I would rename the `titan-compiler` dir just to `pallene` instead of `pallene-compiler` .

**Comment by hugomg** [comment]
Fair enough. I updated the TODO accordingly.

**Comment by hugomg** [comment]
Done! Thanks for the help, @pjpollina!
