### ISSUE TITLE
Use a faster C compiler to run the test suite.

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene#252]
We might be able to speed up the test suite by changing to a faster C compiler. For example, currently we always tell the C compiler to use -O2 optimization but with -O0 we would get better compilation speeds. I measured running the coder_spec test suite and with -O2 it took 5.2 seconds while with -O0 it took 3.7 seconds.

We should add a way to control the C compiler flags, either via environment variables or via pallenec command line options. 

Another thing that might help is to tell the C compiler to go directly from the .c file to the .o file, without generating an intermediary .s file. I didn't measure this part though.

**Comment by mambrozio** [comment]
Wouldn't this be a double edged sword? The test suite should behave the same as we expect production code to behave. An -O2 optimization flag may reveal bugs in our generated code if for example, we rely on undefined behaviours, or make tests that an optimization may deem unnecessary but in fact should be made. There are some cases that these bugs are present in the -O2 version and not in the -O0 version.

[This article](https://lwn.net/Articles/342330/) goes through a bug in the Linux kernel that appeared, in part, because of a GCC optimization:
> This is where the next interesting step in the chain of failures happens: the GCC compiler will, by default, optimize the NULL test out. The reasoning is that, since the pointer has already been dereferenced (and has not been changed), it cannot be NULL. So there is no point in checking it. Once again, this logic makes sense most of the time, but not in situations where NULL might actually be a valid pointer.

There is also [this](https://my.eng.utah.edu/~cs5785/slides-f10/Dangerous+Optimizations.pdf) presentation with other examples.

We should test going directly from the .c file to the .o file and see if it provides an improvement. But personally, I don't think it is a good idea to make tests run in -O0.

What do you think?

**Comment by hugomg** [comment]
We might be able to get the best of both worlds if we use -O0 during development and -O2 on the Travis CI tests.

**Comment by mambrozio** [comment]
If PR #289 gets accepted the way it is now, it should be possible to do this in a fairly simple manner. We only need to put a `CFLAGS="-O0"` in test-project script and for Travis CI tests do nothing, since the default behaviour is -O2.
