### ISSUE TITLE
Request for a statement concerning current state and roadmap of Pallene

### ISSUE THREAD

**Issue by rochus-keller** [pallene-lang/pallene#331]
Can you please comment on these two posts. 

http://lua-users.org/lists/lua-l/2020-09/msg00090.html

https://old.reddit.com/r/lua/comments/j9x33f/arewefastyet_benchmark_suite_applied_to_different/ (the EDIT part)

Thanks.

**Comment by hugomg** [comment]
The idea behind Pallene is to rewrite the performance-sensitive parts in Pallene and glue them together with Lua. It's intended to be used together with Lua, not as a complete replacement for Lua.

That said, for the parts that can be rewritten in Pallene, the goal is that it should be just a matter of adding type annotations. When this is not possible because Pallene doesn't implement some kind of feature then it depends: it could be a feature that we just haven't added to Pallene yet or it could be a feature that isn't ever likely to be added, because it would hurt the performance.

For example, closures and nested functions would be in the first category. There is nothing stopping them from being added to Pallene, other than the implementation is tricky and someone needs to put in the work to figure out how to do it.

Metatables for operator overloading is something that we are less likely to add. For example, it is important for performance that if you declare something as an `integer` it really is an integer and not some kind of object that behaves as an integer because of metamethods.

One kind of metatable thing that I could see us adding to Pallene eventually would be support for OO-style programming where you define methods for a Pallene `record` that can be called with a `x:foo()` syntax instead of `foo(x)`. For now, the workaround if you want to do that is to define all the functions in Pallene but do the metatable manipulation in Lua.

Does this answer your question?

**Comment by rochus-keller** [comment]
Thanks for your repsonse. We can already today rewrite performance sensitive parts in any statically compiled language which supports the C ABI. In LuaJIT there is even the FFI which is very efficient. To have an added value, Pallene should be as similar and capable as Lua. Today there are syntactical similarities, but it's a different language, not even a subset of Lua. So why should we prefer Pallene over any other statically compiled language? If I have to re-design my Lua application for compatibility with the restricted expressivnes of Pallene, then a large part of the advantages is lost. This is the are-we-fast-yet benchmark. There is an official Lua implementation that meets the criteria of the benchmark (e.g. idiomatic use of the language). The application is obviously performance sensitive, but I would have to change quite a lot of it to make it representable with Pallene. In my view, there is a considerable mismatch between need and solution.

**Comment by hugomg** [comment]
> We can already today rewrite performance sensitive parts in any statically typed language which supports the C ABI

If you have code that is using lot's of Lua tables and objects then using the Lua-C API can be quite slow. Pallene can be much faster in those cases because it know how to use Lua tables without needing to go through the Lua-C API.

**Comment by rochus-keller** [comment]
> If you have code that is frequently accessing Lua tables and objects then using the Lua-C API can be quite slow.

Why? Because of the additional function calls? Type information shouldn't matter a lot when reading/writing to objects.

> can be much faster in those cases because it knows how to use Lua tables without needing to go through the Lua-C API

So could we achieve the same effect by just inlining these calls?

**Comment by hugomg** [comment]
It has to do with the cost of crossing a language boundary. You may need to convert the data from one language to the other. The API also needs to push and pop things from the Lua stack, check the types of the arguments to the API calls, etc.

>  So could we achieve the same effect by just inlining these calls? Or by bypassing the stack?

At a very high level this is what Pallene is doing. Instead of doing everything via the Lua stack, Pallene directly accesses the the relevant Lua objects via pointers.

However, this is would be hard to do with other typed languages because if you exposed pointers to Lua objects in the Lua API then you would need to come up with a way for the Lua garbage collector to know when the other language is holding pointers to a a given Lua objects . That's because if the other language is holding a pointer to an object it means you can't garbage collect that object. When the API is designed this way with direct access to pointers it is easy for the programmer to shoot themselves in the foot. For example, in Python the programmer using the API is tasked with manually incrementing and decrementing reference counts and if they do that wrong the program can segfault. (Not to mention that the reference counting itself introduces a substantial performance overhead for certain workloads,)

There is also a backwards compatibility problem if you expose those low level details in the API. These parts of Lua frequently change from one version to the next and it would break many programs if they were exposed as parts of the API. In Pallene it is not as bit of a problem because we only need to update the compiler in a couple of places when a new Lua version comes out.

**Comment by rochus-keller** [comment]
> then you would need to come up with a way for the Lua garbage collector to know when the other language is holding pointers to a a given Lua objects

Shouldn't be too difficult to add a temporary array of pointers to the root set of the GC.

> There is also a backwards compatibility problem if you expose those low level details in the API. 

Well, Pallene has the same issue. With an API it's even easier because you immediately can see where it breaks without generating code and trying to map to the generator.

I will take a look at the possibility to replace the Lua 5.4.1 API by something more efficient.
