### ISSUE TITLE
a couple of questions regarding developer's editor ...

### ISSUE THREAD

**Issue by JLPLabs** [pallene-lang/pallene#460]
A few low priority questions...

1. What editor(s) does the team use when writing **.pln** files?
2. Do you have syntax coloring of Pallene files in your editor? If so, how?
3. Do you have error highlighting of Pallene files in your editor? If so, how?

I normally use `vim`, and am able to use the Pallene .editorconfig file... but would really get value from **syntax coloring** and **error highlighting** as I work on a Pallene file.

Any insights are welcome!

Many thanks!

**Comment by JLPLabs** [comment]
_Perhaps these questions should have been posted in the "Discussions" section? If so, I'm sorry for the added noise to the issues list._

_(I am happy to post them where is appropriate)_

**Comment by hugomg** [comment]
The discussion section isn't well advertised, maybe I should add a note to the README somewhere... But it's OK, we can use this issue for now, and use the discussion tab for future ones.

Going back to your questions:

1. What editor(s) does the team use when writing .pln files?

All sorts of editors. In practice, when working on the compiler we tend to edit Lua files more than we edit Pallene ones, so any editor that works well for Lua is OK.

The only thing that we ask is that people try to use the Editorconfig plugin, to ensure that the indentation is right.

2. Do you have syntax coloring of Pallene files in your editor? If so, how?

I tell my editor to highlight pln files as if they they were Lua. It's not perfect, because the highlighting doesn't recognize the type annotations. But it's better than nothing.

```
augroup vimrc_syntax | autocmd!
    autocmd BufNewFile,BufRead *.pln   setlocal syntax=lua
augroup end
```

3. Do you have error highlighting of Pallene files in your editor? If so, how?

I don't know how to do that, but if you know an easy way then I'm glad to receive suggestions!

**Comment by srijan-paul** [comment]
> Do you have error highlighting of Pallene files in your editor? If so, how?

Does this mean errors that are thrown by the pallene compilers on `.pln` files or errors by a lua linter?

**Comment by hugomg** [comment]
Let's continue this discussion on https://github.com/pallene-lang/pallene/discussions/461
