### ISSUE TITLE
unitialized.lua does not detect some corner cases.

### ISSUE THREAD

**Issue by srijan-paul** [pallene-lang/pallene#480]
Cases like the one below seem to pass the use-before-init checks.
```lua
local x: integer;
if false then  x = 1 end
local function g(): integer
	return x + 10 -- use before init, but compiles anyway
end
```

Removing the `if false` seems to work.
Keeping the if-statement and getting rid of the `+ 10` also appears to work just fine,

**Comment by hugomg** [comment]
I think I found another corner case. If a variable is captured mutably, I believe we are not checking if the box contents are initialized.

```lua
local x: integer
local function g()
    x = x + 1
end
```

Perhaps we can solve this in the uninitialized.lua by treating the boxed variables specially.  (This would require having the assignment_conversion mark which variables are boxes). In the uninitialized.lua, when we analyze the function that creates the box, verify if the contents of the box are initialized, instead of verifying if the box itself is initialized. That is, an initialization for a box variable consists of a SetField, instead of a dst. If the box contents are not initialized by the time the box is captured by a SetUpvalues, then raise a compile-time error.

Another option would be to pessimistically forbid any mutable capture of an uninitialized variable. That is, we could tell the assignment_conversion to only allow a mutable capture if the declaration of the variable contains an initializer. (This idea assumes that uninitialized mutable captures are not common and that programmer should be able to work around the limitation if they really need to).

What do you think would be the better thing to do?

**Comment by srijan-paul** [comment]
I think the former is a better idea. Since it's possible for us to actually take care of this without having to pose any restrictions on the programmer.

**Comment by hugomg** [comment]
The thing I was more worried about is treating the boxes specially and having to add extra information to the AST. But maybe that is not so bad:

1. If we wanted, we could extend the uninitialized.lua to also track initialization of record fields. (We don't need to do this now, but it's possible in principle by extending the dataflow equations)
2. Knowing if something is a box or not is necessary for accurate error messages in the uninitialized.lua.
3. We are already tracking if something is a box, with the `is_upvalue_box` field.

**Comment by srijan-paul** [comment]
I was thinking about a different approach to this problem.
The problem only occurs when we're inspecting a **mutable upvalue**.
Because, from the verification pass's POV, there is a `ir.Cmd.NewTable` instruction that initializes the variable to a record.

If we added a `is_upvalue_box` field to the `NewTable` instruction, `uninitialized.lua` knows that this instruction should not count as initialization. The implementation for this is much simpler, but it might also come off as odd because of the specific `is_upvalue_box` field. 

I tested this on a separate branch and it took 2 lines of code.

**Comment by hugomg** [comment]
Did this change solve the use-before-init bug? How? The part that I don't understand is that I think what you said would be about having the compiler not complain about things that it used to complain, but the bug is the opposite of that.


About the extra field, I do agree that the IR must have a way to tell apart an upvalue box from a regular variable. I don't know if we necessarily have to edit the IR though. Don't we already have a field for that in the types.T ?

**Comment by srijan-paul** [comment]
> Did this change solve the use-before-init bug? How?

1. For every `ir.Cmd.Upvalue` record -> do not count it as an initializer for variables (since it's artificial and introduced by the compiler).
2. For every `ir.Cmd.SetField` -> if the `rec_typ` is an upvalue box type, then count it as an initializer.

I admit that this is very hacky but it's the neatest solution I could come up with LoC wise that didn't require any extra table baggage being passed from one pass to the next.

> I don't know if we necessarily have to edit the IR though.

Currently, we only use the `ir.Cmd.UpvalueRecord` to initialize mutable upvalues that don't have an init expression in the source code. If we keep this special instruction for this very purpose, then it turns out we don't need to add any extra annotations to the IR :D

I'll open a PR in a bit since I think that might help.
