### ISSUE TITLE
Create temporary files with temporary names

### ISSUE THREAD

**Issue by gligneul** [pallene-lang/pallene#71]
Currently, if I have a `.c` file with the same name of the `.pallene` file, the compiler overwrites the `.c` file with a temporary C code.
Then, at the end of the compilation the file is wiped.
Instead of overwriting a possible existent file, the compiler should use something like mktmp to create a unique file.

**Comment by hugomg** [comment]
IIRC, the reason it works like this right now is that Lua's os.tmpname function produces doesn't allow you to create file names with a chosen extension. (And file extensions are important for our logic).

If we add a luaposix depencency we could use mkstemp. 

Btw I think this is related with #17

**Comment by ahmedkrmn** [comment]
Can I start working on this, or is it depending on issue #16?

**Comment by hugomg** [comment]
I don't think this one depends on #16. On the contrary: solving this will help #16 and #17 a bit, because it would mean that pallenec is affecting less files in the current working directory.

If you want to have a crack at this, the first place to look at would be `driver.lua` and `c_compiler.lua`.

The main obstacle to overcome is that the new temporary files are not going to have a ".c" or ".o" extension, which might require changing the code in a couple of places. For example, it might be necessary to pass the "-x" flag to the C compiler.

**Comment by ahmedkrmn** [comment]
@hugomg I was thinking about just appending `_temp_` or even a randomly string before all the generated files names.
Would that suffice or should I follow your suggestions?

**Comment by hugomg** [comment]
I'm not sure those strategies would guarantee that the file doesn't already exist.
